name: CI

on:
  push:
    branches:
      - master
      - test-ci
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - plugin: "livesync"
          - plugin: "payment_paypal"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache-pip
        with:
          path: .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
      - name: Setup Python
        uses: actions/setup-python@v1
        if: steps.cache-pip.outputs.cache-hit != 'true'
        with:
          python-version: 3.9
      - name: Get branch name (base or pull_request)
        shell: bash
        run: |
          echo $(echo ${GITHUB_HEAD_REF:-${GITHUB_REF}} | sed 's/.*\///')
          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF}} | sed 's/.*\///')" >> $GITHUB_ENV
      - name: Install python dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -U pip setuptools
          pip install wheel
          pip install -e git+https://github.com/indico/indico.git@master#egg=indico
      - name: Activate virtualenv for later steps
        run: |
          echo "VIRTUAL_ENV=$(pwd)/.venv" >> $GITHUB_ENV
          echo "$(pwd)/.venv/bin" >> $GITHUB_PATH
      - name: Install
        run: |
          cd "${GITHUB_WORKSPACE}/${{ matrix.plugin }}"
          pip install -e .
      - name: Test
        run: |
          pytest "${GITHUB_WORKSPACE}/${{ matrix.plugin }}"
